# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_monitor.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(494, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_main = QtWidgets.QLabel(self.centralwidget)
        self.label_main.setGeometry(QtCore.QRect(190, 10, 102, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_main.setFont(font)
        self.label_main.setObjectName("label_main")
        self.label_error_data_color = QtWidgets.QLabel(self.centralwidget)
        self.label_error_data_color.setGeometry(QtCore.QRect(30, 420, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_error_data_color.setFont(font)
        self.label_error_data_color.setObjectName("label_error_data_color")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 40, 421, 371))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_kistler = QtWidgets.QLabel(self.layoutWidget)
        self.label_kistler.setObjectName("label_kistler")
        self.gridLayout.addWidget(self.label_kistler, 0, 0, 1, 1)
        self.label_vehicle = QtWidgets.QLabel(self.layoutWidget)
        self.label_vehicle.setObjectName("label_vehicle")
        self.gridLayout.addWidget(self.label_vehicle, 0, 1, 1, 1)
        self.textBrowser_kistler_data = QtWidgets.QTextBrowser(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.textBrowser_kistler_data.setFont(font)
        self.textBrowser_kistler_data.setObjectName("textBrowser_kistler_data")
        self.gridLayout.addWidget(self.textBrowser_kistler_data, 1, 0, 1, 1)
        self.textBrowser_vehicle_data = QtWidgets.QTextBrowser(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.textBrowser_vehicle_data.setFont(font)
        self.textBrowser_vehicle_data.setObjectName("textBrowser_vehicle_data")
        self.gridLayout.addWidget(self.textBrowser_vehicle_data, 1, 1, 1, 1)
        self.label_diff = QtWidgets.QLabel(self.layoutWidget)
        self.label_diff.setObjectName("label_diff")
        self.gridLayout.addWidget(self.label_diff, 2, 0, 1, 2)
        self.textBrowser_diff_data = QtWidgets.QTextBrowser(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.textBrowser_diff_data.setFont(font)
        self.textBrowser_diff_data.setObjectName("textBrowser_diff_data")
        self.gridLayout.addWidget(self.textBrowser_diff_data, 3, 0, 1, 1)
        self.label_error = QtWidgets.QLabel(self.layoutWidget)
        self.label_error.setObjectName("label_error")
        self.gridLayout.addWidget(self.label_error, 4, 0, 1, 1)
        self.textBrowser_error_data = QtWidgets.QTextBrowser(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.textBrowser_error_data.setFont(font)
        self.textBrowser_error_data.setObjectName("textBrowser_error_data")
        self.gridLayout.addWidget(self.textBrowser_error_data, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 494, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyQt5 ROS2 APP"))
        self.label_main.setText(_translate("MainWindow", "車速モニター"))
        self.label_error_data_color.setText(_translate("MainWindow", "Error Rate Status"))
        self.label_kistler.setText(_translate("MainWindow", "光学車速計km/h"))
        self.label_vehicle.setText(_translate("MainWindow", "実車両速度km/h"))
        self.textBrowser_kistler_data.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:30pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">100.00</span></p></body></html>"))
        self.textBrowser_vehicle_data.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:30pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">100.0</span></p></body></html>"))
        self.label_diff.setText(_translate("MainWindow", "差分（光学式車速計 - 車両速度）km/h"))
        self.textBrowser_diff_data.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:30pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">100.0</span></p></body></html>"))
        self.label_error.setText(_translate("MainWindow", "誤差率%"))
        self.textBrowser_error_data.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:30pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">100.00</span></p></body></html>"))
